# Generated by Django 4.2.5 on 2023-11-23 01:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_backuphistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
